import type { SolarConfig } from '../types/solar'

export type FieldType = 'number' | 'currency' | 'percent' | 'toggle' | 'select'

export interface ConfigField {
  key: keyof SolarConfig
  label: string
  helper: string
  info: string
  type: FieldType
  min?: number
  max?: number
  step?: number
  suffix?: string
  options?: string[]
  disabled?: (config: SolarConfig) => boolean
  emphasizeLinks?: boolean
}

export interface ConfigSection {
  id: string
  title: string
  description: string
  fields: ConfigField[]
}

export const CONFIG_SECTIONS: ConfigSection[] = [
  {
    id: 'utility',
    title: 'Utility & Financials',
    description: 'Baseline electricity costs and incentives drive every downstream calculation.',
    fields: [
      {
        key: 'utilityCostPerKwh',
        label: 'Current Cost per kWh',
        helper: 'Utility rate you currently pay before solar.',
        info: 'Most US utilities range between $0.12 and $0.28 per kWh. Use your latest bill for accuracy.',
        type: 'currency',
        min: 0.05,
        max: 1,
        step: 0.005,
        suffix: '$/kWh',
      },
      {
        key: 'netMetering',
        label: 'Enable Net Metering',
        helper: 'Toggle if your utility credits exported energy.',
        info: 'Net metering lets you bank or sell surplus energy back to the grid. Rules vary by state.',
        type: 'toggle',
      },
      {
        key: 'netMeteringSellRate',
        label: 'Sell-Back Rate',
        helper: 'Value paid per exported kWh.',
        info: 'If your utility offers avoided cost or retail rate credit, enter that amount.',
        type: 'currency',
        min: 0,
        max: 1,
        step: 0.005,
        suffix: '$/kWh',
        disabled: (config) => !config.netMetering,
      },
      {
        key: 'utilityInflationRate',
        label: 'Utility Inflation Rate',
        helper: 'Annual increase in grid energy prices.',
        info: 'Historically utilities inflate 2-4% each year. Higher inflation accelerates solar savings.',
        type: 'percent',
        min: 0,
        max: 15,
        step: 0.25,
        suffix: '%',
      },
      {
        key: 'monthlyUsage',
        label: 'Average Monthly Usage',
        helper: 'Typical consumption from your bills.',
        info: 'Enter average kWh usage so the model can compare production vs. demand.',
        type: 'number',
        min: 100,
        max: 3000,
        step: 10,
        suffix: 'kWh',
      },
      {
        key: 'federalTaxCredit',
        label: 'Federal Tax Credit',
        helper: 'Percentage of eligible costs you can claim.',
        info: 'The US ITC is 30% through 2032 for qualifying projects.',
        type: 'percent',
        min: 0,
        max: 40,
        step: 1,
        suffix: '%',
      },
    ],
  },
  {
    id: 'solarAccess',
    title: 'Solar Access',
    description: 'Sun hours vary widely by location - use authoritative data for accuracy.',
    fields: [
      {
        key: 'peakSunHours',
        label: 'Average Peak Sun Hours',
        helper: 'Average daily equivalent of full sun.',
        info: 'Look up your address on Google Project Sunroof or NREL PVWatts for precise data.',
        type: 'number',
        min: 2,
        max: 7,
        step: 0.1,
        suffix: 'hrs/day',
        emphasizeLinks: true,
      },
    ],
  },
  {
    id: 'panels',
    title: 'Solar Panel System',
    description: 'Define the array size, quality, and hardware assumptions.',
    fields: [
      {
        key: 'panelCount',
        label: 'Number of Panels',
        helper: 'Total modules planned for the array.',
        info: 'Count every module including those on secondary roof faces.',
        type: 'number',
        min: 1,
        max: 80,
        step: 1,
      },
      {
        key: 'panelWattage',
        label: 'Wattage per Panel (STC)',
        helper: 'Nameplate rating at standard test conditions.',
        info: 'Residential panels commonly fall between 370W and 440W today.',
        type: 'number',
        min: 250,
        max: 600,
        step: 10,
        suffix: 'W',
      },
      {
        key: 'panelEfficiency',
        label: 'Panel Efficiency',
        helper: 'Module conversion efficiency.',
        info: 'Premium monocrystalline modules land near 21%. Lower numbers reduce production.',
        type: 'percent',
        min: 14,
        max: 24,
        step: 0.1,
        suffix: '%',
      },
      {
        key: 'panelDegradationRate',
        label: 'Annual Degradation Rate',
        helper: 'Expected output loss per year.',
        info: 'Most Tier-1 modules warrant <0.5% annual degradation.',
        type: 'percent',
        min: 0.1,
        max: 2,
        step: 0.05,
        suffix: '%',
      },
      {
        key: 'costPerPanel',
        label: 'Cost per Panel',
        helper: 'Hardware cost per module.',
        info: 'Use delivered cost, not installed price.',
        type: 'currency',
        min: 100,
        max: 600,
        step: 5,
        suffix: '$',
      },
    ],
  },
  {
    id: 'bos',
    title: 'Balance of System',
    description: 'Capture inverter and wiring performance penalties.',
    fields: [
      {
        key: 'inverterType',
        label: 'Inverter Type',
        helper: 'Select the topology you plan to use.',
        info: 'String inverters are cost effective; microinverters improve shading tolerance.',
        type: 'select',
        options: ['String', 'Micro'],
      },
      {
        key: 'inverterEfficiency',
        label: 'Inverter Efficiency',
        helper: 'Conversion efficiency from DC to AC.',
        info: 'Modern inverters typically exceed 96%.',
        type: 'percent',
        min: 90,
        max: 99.9,
        step: 0.1,
        suffix: '%',
      },
      {
        key: 'inverterCost',
        label: 'Total Inverter Cost',
        helper: 'All inverter hardware.',
        info: 'Include optimizers or microinverters if applicable.',
        type: 'currency',
        min: 500,
        max: 10000,
        step: 100,
        suffix: '$',
      },
      {
        key: 'cablingLoss',
        label: 'Cabling/Wiring Loss',
        helper: 'Percent of production lost to wiring.',
        info: 'Tight designs target 2% or less.',
        type: 'percent',
        min: 0,
        max: 10,
        step: 0.25,
        suffix: '%',
      },
    ],
  },
  {
    id: 'battery',
    title: 'Battery Storage',
    description: 'Optional storage extends resilience and increases self-consumption.',
    fields: [
      {
        key: 'batteryEnabled',
        label: 'Enable Battery',
        helper: 'Toggle to include storage economics.',
        info: 'Disable if you are modeling solar-only systems.',
        type: 'toggle',
      },
      {
        key: 'batteryCapacity',
        label: 'Battery Capacity',
        helper: 'Usable nameplate capacity.',
        info: 'Tesla Powerwall is 13.5 kWh for reference.',
        type: 'number',
        min: 0,
        max: 40,
        step: 0.5,
        suffix: 'kWh',
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryDoD',
        label: 'Depth of Discharge',
        helper: 'Percent of capacity that is usable.',
        info: 'Most lithium chemistries allow 80-95% DoD.',
        type: 'percent',
        min: 50,
        max: 100,
        step: 1,
        suffix: '%',
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryPower',
        label: 'Continuous Power Output',
        helper: 'Maximum sustained discharge power.',
        info: 'Determines how many loads you can run during an outage.',
        type: 'number',
        min: 1,
        max: 15,
        step: 0.5,
        suffix: 'kW',
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryCost',
        label: 'Total Battery Cost',
        helper: 'All battery hardware and integration.',
        info: 'Include gateway, subpanel work, and labor premiums.',
        type: 'currency',
        min: 0,
        max: 50000,
        step: 250,
        suffix: '$',
        disabled: (config) => !config.batteryEnabled,
      },
    ],
  },
  {
    id: 'upfront',
    title: 'Upfront & Other Costs',
    description: 'Capture soft costs to finalize capital requirements.',
    fields: [
      {
        key: 'mountingCost',
        label: 'Mounting Hardware Cost',
        helper: 'Rails, clamps, flashings, ballast, etc.',
        info: 'Include roof reinforcement if required.',
        type: 'currency',
        min: 0,
        max: 20000,
        step: 100,
        suffix: '$',
      },
      {
        key: 'monitoringCost',
        label: 'Monitoring Equipment Cost',
        helper: 'Consumption CTs, communication gear, portals.',
        info: 'Keep ongoing subscription fees separate for now.',
        type: 'currency',
        min: 0,
        max: 10000,
        step: 50,
        suffix: '$',
      },
      {
        key: 'laborCost',
        label: 'Installation Labor Cost',
        helper: 'Include subcontractors and permitting.',
        info: 'Labor varies by region; include electrical upgrades.',
        type: 'currency',
        min: 0,
        max: 50000,
        step: 250,
        suffix: '$',
      },
      {
        key: 'otherFees',
        label: 'Other One-Time Fees',
        helper: 'Permits, engineering, interconnection, misc.',
        info: 'Any upfront cost not listed above.',
        type: 'currency',
        min: 0,
        max: 20000,
        step: 100,
        suffix: '$',
      },
    ],
  },
]
