import type { SolarConfig } from '../types/solar'

export type FieldType = 'number' | 'currency' | 'percent' | 'toggle' | 'select' | 'modeToggle' | 'bulkPricing' | 'loanEstimate'

export interface ConfigField {
  key: keyof SolarConfig
  label: string
  helper: string
  info: string
  type: FieldType
  min?: number
  max?: number
  step?: number
  suffix?: string
  options?: string[]
  disabled?: (config: SolarConfig) => boolean
  emphasizeLinks?: boolean
}

export interface ConfigSection {
  id: string
  title: string
  description: string
  fields: ConfigField[]
}

export const CONFIG_SECTIONS: ConfigSection[] = [
  {
    id: 'utility',
    title: 'Utility & Financials',
    description: 'Baseline electricity costs and incentives drive every downstream calculation.',
    fields: [
      {
        key: 'utilityCostPerKwh',
        label: 'Current Cost per kWh',
        helper: 'Utility rate you currently pay before solar.',
        info: 'Most US utilities range between $0.12 and $0.28 per kWh. Use your latest bill for accuracy.',
        type: 'currency',
        min: 0.05,
        max: 1,
        step: 0.005,
        suffix: '$/kWh',
      },
      {
        key: 'netMetering',
        label: 'Enable Net Metering',
        helper: 'Toggle if your utility credits exported energy.',
        info: 'Net metering lets you bank or sell surplus energy back to the grid. Rules vary by state.',
        type: 'toggle',
      },
      {
        key: 'netMeteringSellRate',
        label: 'Sell-Back Rate',
        helper: 'Value paid per exported kWh.',
        info: 'If your utility offers avoided cost or retail rate credit, enter that amount.',
        type: 'currency',
        min: 0,
        max: 1,
        step: 0.005,
        suffix: '$/kWh',
        disabled: (config) => !config.netMetering,
      },
      {
        key: 'utilityInflationRate',
        label: 'Utility Inflation Rate',
        helper: 'Annual increase in grid energy prices.',
        info: 'Historically utilities inflate 2-4% each year. Higher inflation accelerates solar savings.',
        type: 'percent',
        min: 0,
        max: 15,
        step: 0.25,
        suffix: '%',
      },
      {
        key: 'monthlyUsage',
        label: 'Average Monthly Usage',
        helper: 'Typical consumption from your bills.',
        info: 'Enter average kWh usage so the model can compare production vs. demand.',
        type: 'number',
        min: 100,
        max: 3000,
        step: 10,
        suffix: 'kWh',
      },
      {
        key: 'federalTaxCredit',
        label: 'Federal Tax Credit',
        helper: 'Percentage of eligible costs you can claim.',
        info: 'The US ITC is 30% through 2032 for qualifying projects.',
        type: 'percent',
        min: 0,
        max: 40,
        step: 1,
        suffix: '%',
      },
    ],
  },
  {
    id: 'solarAccess',
    title: 'Solar Access',
    description: 'Sun hours vary widely by location - use authoritative data for accuracy.',
    fields: [
      {
        key: 'sunHoursMode',
        label: 'Sun Hours Input Mode',
        helper: 'Choose daily average or total yearly hours.',
        info: 'Daily mode (default) is standard. Yearly mode matches Google Solar API output.',
        type: 'modeToggle',
        options: ['daily', 'yearly'],
      },
      {
        key: 'peakSunHours',
        label: 'Peak Sun Hours',
        helper: 'Average daily equivalent of full sun OR total yearly hours.',
        info: 'Look up your address on Google Project Sunroof or NREL PVWatts for precise data.',
        type: 'number',
        min: 2,
        max: 8760,
        step: 0.1,
        suffix: 'hrs',
        emphasizeLinks: true,
      },
    ],
  },
  {
    id: 'panels',
    title: 'Solar Panel System',
    description: 'Define the array size, quality, and hardware assumptions.',
    fields: [
      {
        key: 'panelCount',
        label: 'Number of Panels',
        helper: 'Total modules planned for the array.',
        info: 'Count every module including those on secondary roof faces.',
        type: 'number',
        min: 1,
        max: 80,
        step: 1,
      },
      {
        key: 'panelWattage',
        label: 'Wattage per Panel (STC)',
        helper: 'Nameplate rating at standard test conditions.',
        info: 'Residential panels commonly fall between 370W and 440W today.',
        type: 'number',
        min: 250,
        max: 600,
        step: 10,
        suffix: 'W',
      },
      {
        key: 'panelEfficiency',
        label: 'Panel Efficiency',
        helper: 'Module conversion efficiency.',
        info: 'Premium monocrystalline modules land near 21%. Lower numbers reduce production.',
        type: 'percent',
        min: 14,
        max: 24,
        step: 0.1,
        suffix: '%',
      },
      {
        key: 'panelDegradationRate',
        label: 'Annual Degradation Rate',
        helper: 'Expected output loss per year.',
        info: 'Most Tier-1 modules warrant <0.5% annual degradation.',
        type: 'percent',
        min: 0.1,
        max: 2,
        step: 0.05,
        suffix: '%',
      },
      {
        key: 'pricingMode',
        label: 'Panel Pricing Mode',
        helper: 'Choose per-panel or bulk package pricing.',
        info: 'Bulk mode: enter total cost for a set quantity (e.g., 24 panels for $6,720).',
        type: 'modeToggle',
        options: ['perUnit', 'bulk'],
      },
      {
        key: 'costPerPanel',
        label: 'Cost per Panel',
        helper: 'Hardware cost per module.',
        info: 'Use delivered cost, not installed price.',
        type: 'currency',
        min: 100,
        max: 600,
        step: 5,
        suffix: '$',
        disabled: (config) => config.pricingMode === 'bulk',
      },
      {
        key: 'panelBulkCount',
        label: 'Bulk Panel Quantity',
        helper: 'Number of panels in bulk package.',
        info: 'E.g., 24 panels in a pallet',
        type: 'bulkPricing',
        min: 1,
        max: 100,
        step: 1,
        disabled: (config) => config.pricingMode !== 'bulk',
      },
      {
        key: 'panelBulkCost',
        label: 'Bulk Package Cost',
        helper: 'Total cost for the bulk quantity.',
        info: 'Calculator will divide by quantity for per-unit cost.',
        type: 'currency',
        min: 100,
        max: 60000,
        step: 100,
        suffix: '$',
        disabled: (config) => config.pricingMode !== 'bulk',
      },
    ],
  },
  {
    id: 'bos',
    title: 'Balance of System',
    description: 'Capture inverter and wiring performance penalties.',
    fields: [
      {
        key: 'inverterType',
        label: 'Inverter Type',
        helper: 'Select the topology you plan to use.',
        info: 'String inverters are cost effective; microinverters improve shading tolerance.',
        type: 'select',
        options: ['String', 'Micro'],
      },
      {
        key: 'inverterEfficiency',
        label: 'Inverter Efficiency',
        helper: 'Conversion efficiency from DC to AC.',
        info: 'Modern inverters typically exceed 96%.',
        type: 'percent',
        min: 90,
        max: 99.9,
        step: 0.1,
        suffix: '%',
      },
      {
        key: 'inverterPricingMode',
        label: 'Inverter Pricing Mode',
        helper: 'Choose per-unit or bulk set pricing.',
        info: 'For microinverters, use bulk mode for a set quantity. For string, per-unit is typical.',
        type: 'modeToggle',
        options: ['perUnit', 'bulk'],
      },
      {
        key: 'inverterCost',
        label: 'Inverter Cost',
        helper: 'Single inverter or per-microinverter cost.',
        info: 'Include optimizers if applicable.',
        type: 'currency',
        min: 500,
        max: 10000,
        step: 100,
        suffix: '$',
        disabled: (config) => config.inverterPricingMode === 'bulk',
      },
      {
        key: 'inverterBulkCount',
        label: 'Inverter Bulk Quantity',
        helper: 'Number of inverters/microinverters in set.',
        info: 'E.g., 24 microinverters',
        type: 'bulkPricing',
        min: 1,
        max: 100,
        step: 1,
        disabled: (config) => config.inverterPricingMode !== 'bulk',
      },
      {
        key: 'inverterBulkCost',
        label: 'Inverter Set Cost',
        helper: 'Total cost for bulk inverter set.',
        info: 'Calculator will divide by quantity.',
        type: 'currency',
        min: 500,
        max: 50000,
        step: 100,
        suffix: '$',
        disabled: (config) => config.inverterPricingMode !== 'bulk',
      },
      {
        key: 'cablingLoss',
        label: 'Cabling/Wiring Loss',
        helper: 'Percent of production lost to wiring.',
        info: 'Tight designs target 2% or less.',
        type: 'percent',
        min: 0,
        max: 10,
        step: 0.25,
        suffix: '%',
      },
    ],
  },
  {
    id: 'battery',
    title: 'Battery Storage',
    description: 'Optional storage extends resilience and increases self-consumption.',
    fields: [
      {
        key: 'batteryEnabled',
        label: 'Enable Battery',
        helper: 'Toggle to include storage economics.',
        info: 'Disable if you are modeling solar-only systems.',
        type: 'toggle',
      },
      {
        key: 'batteryCapacity',
        label: 'Battery Capacity',
        helper: 'Usable nameplate capacity.',
        info: 'Tesla Powerwall is 13.5 kWh for reference.',
        type: 'number',
        min: 0,
        max: 40,
        step: 0.5,
        suffix: 'kWh',
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryDoD',
        label: 'Depth of Discharge',
        helper: 'Percent of capacity that is usable.',
        info: 'Most lithium chemistries allow 80-95% DoD.',
        type: 'percent',
        min: 50,
        max: 100,
        step: 1,
        suffix: '%',
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryPower',
        label: 'Continuous Power Output',
        helper: 'Maximum sustained discharge power.',
        info: 'Determines how many loads you can run during an outage.',
        type: 'number',
        min: 1,
        max: 15,
        step: 0.5,
        suffix: 'kW',
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryPricingMode',
        label: 'Battery Pricing Mode',
        helper: 'Choose per-unit or bulk system pricing.',
        info: 'Use bulk for battery+inverter packages.',
        type: 'modeToggle',
        options: ['perUnit', 'bulk'],
        disabled: (config) => !config.batteryEnabled,
      },
      {
        key: 'batteryCost',
        label: 'Battery Cost',
        helper: 'Single battery unit cost.',
        info: 'Include gateway and integration.',
        type: 'currency',
        min: 0,
        max: 50000,
        step: 250,
        suffix: '$',
        disabled: (config) => !config.batteryEnabled || config.batteryPricingMode === 'bulk',
      },
      {
        key: 'batteryBulkCount',
        label: 'Battery Bulk Quantity',
        helper: 'Number of batteries in system.',
        info: 'E.g., 2 Powerwalls',
        type: 'bulkPricing',
        min: 1,
        max: 10,
        step: 1,
        disabled: (config) => !config.batteryEnabled || config.batteryPricingMode !== 'bulk',
      },
      {
        key: 'batteryBulkCost',
        label: 'Battery System Cost',
        helper: 'Total cost for all batteries.',
        info: 'Complete system price.',
        type: 'currency',
        min: 0,
        max: 200000,
        step: 1000,
        suffix: '$',
        disabled: (config) => !config.batteryEnabled || config.batteryPricingMode !== 'bulk',
      },
    ],
  },
  {
    id: 'financing',
    title: 'Financing Options',
    description: 'Configure cash purchase or loan financing with AI-powered rate estimation.',
    fields: [
      {
        key: 'financingMode',
        label: 'Financing Mode',
        helper: 'Choose between cash purchase or loan financing.',
        info: 'Cash: pay upfront with tax credit. Loan: finance with monthly payments.',
        type: 'modeToggle',
        options: ['cash', 'loan'],
      },
      {
        key: 'loanAmount',
        label: 'Loan Amount',
        helper: 'Total amount to finance.',
        info: 'Can be full system cost or partial (with down payment).',
        type: 'currency',
        min: 1000,
        max: 200000,
        step: 1000,
        suffix: '$',
        disabled: (config) => config.financingMode !== 'loan',
      },
      {
        key: 'loanTermYears',
        label: 'Loan Term',
        helper: 'Length of loan in years.',
        info: 'Typical solar loans range from 10-25 years.',
        type: 'number',
        min: 5,
        max: 30,
        step: 1,
        suffix: 'years',
        disabled: (config) => config.financingMode !== 'loan',
      },
      {
        key: 'creditScore',
        label: 'Credit Score',
        helper: 'Your FICO score for rate estimation.',
        info: 'Used by AI to estimate loan interest rate. Higher score = lower rate.',
        type: 'loanEstimate',
        min: 300,
        max: 850,
        step: 10,
        disabled: (config) => config.financingMode !== 'loan',
      },
      {
        key: 'loanInterestRate',
        label: 'Interest Rate',
        helper: 'Annual percentage rate (APR).',
        info: 'AI estimates based on credit score, or enter your actual rate offer.',
        type: 'percent',
        min: 0,
        max: 25,
        step: 0.1,
        suffix: '%',
        disabled: (config) => config.financingMode !== 'loan',
      },
    ],
  },
  {
    id: 'upfront',
    title: 'Upfront & Other Costs',
    description: 'Capture soft costs to finalize capital requirements.',
    fields: [
      {
        key: 'mountingCost',
        label: 'Mounting Hardware Cost',
        helper: 'Rails, clamps, flashings, ballast, etc.',
        info: 'Include roof reinforcement if required.',
        type: 'currency',
        min: 0,
        max: 20000,
        step: 100,
        suffix: '$',
      },
      {
        key: 'monitoringCost',
        label: 'Monitoring Equipment Cost',
        helper: 'Consumption CTs, communication gear, portals.',
        info: 'Keep ongoing subscription fees separate for now.',
        type: 'currency',
        min: 0,
        max: 10000,
        step: 50,
        suffix: '$',
      },
      {
        key: 'laborCost',
        label: 'Installation Labor Cost',
        helper: 'Include subcontractors and permitting.',
        info: 'Labor varies by region; include electrical upgrades.',
        type: 'currency',
        min: 0,
        max: 50000,
        step: 250,
        suffix: '$',
      },
      {
        key: 'otherFees',
        label: 'Other One-Time Fees',
        helper: 'Permits, engineering, interconnection, misc.',
        info: 'Any upfront cost not listed above.',
        type: 'currency',
        min: 0,
        max: 20000,
        step: 100,
        suffix: '$',
      },
    ],
  },
]
